### ISSUE TITLE
Update 2017-10-11 ~ Build Well R9.1

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#40] opened 2017-10-12 05:30 UTC
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31480419-a01138d8-aed2-11e7-8b40-ba93e9a0d9b9.png)

# Full Screen: [Build Well R9.1]( http://ladybug-tools.github.io/spider/sandbox/build-well/index.html )

I was about to give up on getting walls with openings into Open Stdio, but finally things began to fall into place. There's still overhangs and fins to be added which should not be difficult. And another horror still to be completed is building orientation. 

The main thing is that the gbXML file is starting to look clean. And we can start to explore what further data can be added by algorithm.

## Change Log
* Build Well R9.1
* Exports gbXML files with exterior wall surfaces with openings that render properly in Open Studio
* Box Shape now equal of L Shape
* Orientation fixed
* Code clean-up

**Comment by mdengusiak** [comment] 2017-10-12 06:37
Hi, 
we slowly getting there :)
I tried to test export but it dose not work for me. Nothing happens when I click it here
![image](https://user-images.githubusercontent.com/14005893/31482327-c75ad3b6-af1f-11e7-88d8-9c1bc74c4a21.png)

can we add units
![image](https://user-images.githubusercontent.com/14005893/31482393-04f72e22-af20-11e7-9073-e3522f4ed7bd.png)

site settings does not work
![image](https://user-images.githubusercontent.com/14005893/31482408-1866939e-af20-11e7-8721-d576e8f06478.png)

**Comment by theo-armour** [comment] 2017-10-12 08:05
> I tried to test export but it dose not work for me. Nothing happens when I click it here

My bad. I wrote the blog post and the forgot to push the new build. Silly me.  ;-)

R9.1 should save OK.


> can we add units

Currently the core of the script is unitless. The issues is that the menus do some validating - and currently the validating numbers are more suited to feet/inches. There has to be a way to reconfigure the menus on the fly.

But now you make me think about: one of the tricks about this script is that it's easy to create new menus. So we could have menus for m/mm. cm or ft/in and be able to switch between them. Which also means menus in different languages. 

> site settings does not work

oops! I forget to copy the page.

Should be back in R9.2 - which i am pushing now

**Comment by mdengusi** [comment] 2017-10-12 12:18
@theo-armour 

I tested again and still can not do it
![image](https://user-images.githubusercontent.com/26113670/31495336-26ed1328-af4f-11e7-8f24-932048525195.png)

site is working perfectly, 
can we copy "Display Settings" it to gbXML viewer as well... it is excellent
![image](https://user-images.githubusercontent.com/26113670/31495396-64994584-af4f-11e7-88c6-5e8d2b349d8c.png)

**Comment by bwelle** [comment] 2017-10-13 07:50
@theo-armour 

The adjacent buildings tab seems broken. None of the inputs when change effect visualization. First time I've seen this. Reminder, main building shouldn't appear here as default, and should be able to be modified by inputs in adjacent building screen.

Actually, I see none of the inputs anywhere in Build Well change the geometry. This an update issue?

**Comment by bwelle** [comment] 2017-10-13 07:52
Wait, I just launched again and now they do work. Strange. thoughts?

**Comment by bwelle** [comment] 2017-10-13 08:04
Integration of Building Settings fields into main shapes...

Are you able to wire in Anton's changes? You currently have them in Building Settings, yet inactive. Facade A, B, C, and D should really be N, S, E, and W, calculated as the building is rotated with parameter orientation. I think I mentioned before, the # of faces does not matter. All faces, whether there are 4 or 40 will all be binned into N, S, E, and W. 

North = 316 deg-44deg
East = 45 deg-134deg
South = 135deg-226deg
West = 227 deg-316deg

So rather than WWR in current Box and L tabs, you could put WWR N, WWR E, WWR S, and WWR W. You can also add a field for Fins. That's in Anton's code too.

**Comment by bwelle** [comment] 2017-10-13 08:06
@theo-armour 
Change Perimeter Depth default to 10 so core zone is valid based on rest of defaults.

**Comment by bwelle** [comment] 2017-10-13 08:07
@theo-armour 
gbXML export seems to work for me. Not sure why not in above comments.

**Comment by bwelle** [comment] 2017-10-13 08:10
@theo-armour 
I still like the unitless approach, but I think you will need an IP/SI version of the tabs (or a field for each shape) since the gbXML export needs to know the units. If the user doesn't specify in the tab, you won't know if they are thinking metric or IP.

**Comment by bwelle** [comment] 2017-10-13 08:10
@theo-armour 

Working on equations spreadsheet now as you requested.

**Comment by bwelle** [comment] 2017-10-13 08:23
@theo-armour 
I'm looking at the gbXML export from Build Well for the L-Shape. Some comments/recommendations...

Windows, walls, and shading all appear correct (except for overhangs not coming in).

There is an issue with how you define floors and roofs. Right now you have two big rectangles for both roof and floor. Since we are not including the "Space Boundary" definitions in the gbXML files, this will cause a problem for us. The roof should be split up into the same number of segments as zones. Meaning, there should be a separate roof object for each zone. So 7 roofs for L, and 5 roofs for Box. Each with the x and y coordinates those of the space footprint, but at the Floor Height z height. Would this take much work to fix? It makes debugging OS geometry definitions much easier, and prevents 2 "roofs" from covering one zone, like what happens now for the core zone.

**Comment by theo-armour** [comment] 2017-10-13 08:56
@bwelle 

> gbXML export seems to work for me. Not sure why not in above comments.

'Control-Shift-R / Hard Reload' is your friend. You cache is full of old files - which often get called instead of newer files. Welcome to the issues of developing software faster than your browser can deal with.

> Roofs

Can do but, wow, coding boredom here we come.

> naming 

can do

> Are you able to wire in Anton's changes? 

Will come in once the new menus start coming in. 

> I guess OS does what it does. 

Yup. And remember that Dan Macumber built his code on top of my demos from 2014. You will note that his HUD looks just like mine. ;-)

> then it would be nice if we could get OS data window to show surfacetype. Not sure how.

We can do this in gbXML viewer. ;-)

***

BTW, should I be thinking about resurrecting my OSM 3D file viewer?

**Comment by bwelle** [comment] 2017-10-13 09:19
@theo-armour 
>Can do but, wow, coding boredom here we come.

Ok, let me discuss with Dan Macumber. The issue is this...most applications "split" a roof or floor surface to just the segment that bounds the space. They define this as Space Boundaries in gbXML file. Both Space Boundaries and Surfaces can be defined. Chien Si said we can ignore space boundaries for simplicity, which means, as is, we would have two roof objects bounding a single space in many cases. I didn't think OS API could support this to correct auto split the surfaces and assign multiple roof or floor objects bounding a single space (since Energy Plus, or the OSM, can't have this. The only definitions in the OSM correspond to space boundaries, i.e. surfaces that exactly bound a space. However, I'm not 100% on this, so let me ask Dan. If it can handle it the way it is, I won't ask you to trudge through coding boredom. If the gbXML API function doesn't like this, we will have to make this change. I'll get back to you on this.

Wait a minute, duh, let me just take the gbXML import as is and run it and see if the OSM is generated correctly and runs. I'll test that now.

>Yup. And remember that Dan Macumber built his code on top of my demos from 2014. You will note that his HUD looks just like mine. ;-)

Aha, interesting. Well, I guess it doesn't really matter what the pop up shows in OS, we won't be viewing OSM files that way or gbXML. We are just using OS now to import and see what's working what's not. It would be nice to see this in gbXML viewer, for once we know we have down what works in OS, we would only use your viewer for visual checks.

>BTW, should I be thinking about resurrecting my OSM 3D file viewer?

Maybe? Seems like OS keeps coming out with new releases so fast I don't know outdated your OSM viewer is. But yeah, when we ping OS API and convert gbXML file to OSM, it would be nice to view the OSM somewhere to make sure the surfaces were split properly from how we have the gbXML file defined currently.

**Comment by bwelle** [comment] 2017-10-13 09:21
@theo-armour 
Reminder on non overhang/fin geometry, the angled interior walls connection core walls to perimeter walls are still not coming through. Though I'm sure you're well aware of that.:)

**Comment by bwelle** [comment] 2017-10-13 11:47
@theo-armour 
Here is the equation [spreadsheet.](https://perkinswill.box.com/s/udcrm0qchu12tt115gr68mxkvctg976o) More details to follow.

**Comment by mdengusiak** [comment] 2017-10-13 17:13
Hi,
 I tested again 
Building Export to gbXML in version `Build Well R9.2` and it does not allow me. I am using Chrome and tested Windows 7/10 Pro.
Does it work for you?

**Comment by bwelle** [comment] 2017-10-13 20:37
@mdengusiak 
Not for me yet. I just cut and past code for now. Even with control shift r doesn't work.

**Comment by theo-armour** [comment] 2017-10-13 20:41
Hm. Checking....

**Comment by bwelle** [comment] 2017-10-13 20:43
@theo-armour 

Sorry, coding boredom looks necessary. Did some testing with API, it has trouble with multilple roof surfaces and floors per space. I'm afraid we will need the roof and floor split by space. Attached sample file generated from [GreenSpaceLive](https://greenspacelive.com/site/building-generator/)

Here is the [file](https://perkinswill.box.com/s/kuyk8lb6rwu3lkby2c9u03odlwkg0gz0) what it would look like, pretty much like the rest of the test gbXML files on Github.

**Comment by theo-armour** [comment] 2017-10-13 20:44
BTW, you must click 'getBuildingData' prior to saving. If gbXML text does
not appear then there's nothing to save

**Comment by theo-armour** [comment] 2017-10-13 20:50
Rats. I have 9.2 exporting edited L shape with success on both Win10 and Chromebook CPUs

**Comment by bwelle** [comment] 2017-10-13 20:50
Aha!!!! That was it.:)

**Comment by bwelle** [comment] 2017-10-13 20:52
As I was up all night I'm running out of steam. I'll pick up the geometry stuff..equations etc. tomorrow. I have a cool new way of doing the parametrics that people will appreciate.:)

**Comment by theo-armour** [comment] 2017-10-13 20:52
![screenshot 2017-10-13 at 1 50 50 pm](https://user-images.githubusercontent.com/547626/31565974-a69acb3c-b01d-11e7-866d-3e9031a38095.png)

Do you see something like this before saving?

**Comment by theo-armour** [comment] 2017-10-13 20:53
@bwelle 

I will add a note to the screen about need to do both steps

**Comment by mdengusiak** [comment] 2017-10-13 21:39
No, I do not see this preview on screen. When I click nothing happen

![image](https://user-images.githubusercontent.com/14005893/31567409-ab5a04ce-b06f-11e7-8199-1c4376a293dd.png)

**Comment by theo-armour** [comment] 2017-10-13 21:42
@mdengusiak 

Did you click on the 'getBuildingData' button prior to trying the 'Save...data...' button?

**Comment by mdengusiak** [comment] 2017-10-13 22:05
Huuurey it works!
THANKS A LOT - this is great!!!!
![image](https://user-images.githubusercontent.com/14005893/31568148-28cb4b90-b073-11e7-9adf-ea330b632080.png)
1. I tested now import to TAS and  file from https://greenspacelive.com/site/building-generator/
and works well 
![image](https://user-images.githubusercontent.com/14005893/31568046-b0b924ba-b072-11e7-9662-61613e6edfce.png)
2. I tested to import your file and is crushing on import ...there must be something simple that is missing...will look at this and let you know
![image](https://user-images.githubusercontent.com/14005893/31568091-f1f87a2a-b072-11e7-8e16-fab584d9f5e0.png)

**Comment by theo-armour** [comment] 2017-10-13 22:18
@mdengusiak 

Currently, the adjacent buildings have have shade surfaceType and name only as fields.

Should we create a special zone for these surfaces?

**Comment by mdengusi** [comment] 2017-10-13 22:28
I will check this and let you know. 
Would be possible to name spaces:
Level_Number i.e. 00_100, 00_101...., 01_100, 01_101 Etc.  I always Start with 100 as sorting is perfect in excel

**Comment by theo-armour** [comment] 2017-10-13 22:36
@mdengusiak 

Yes, we could generate a space (and zone) for each adjacent building. Would this help with creating better calculations downstream?

**Comment by bwelle** [comment] 2017-10-13 23:43
Nope. Shading buildings can’t have zones. Just 5 shading surfaces for a box.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by theo-armour** [comment] 2017-10-14 00:16
@bwelle 

On a complex thread like this one, it's usually a good idea to review the entire thread. 

@chiensiTB 
We are talking about our shade surfaceTypes in gbXML files creating unrecoverable errors in FZK and what to do about them. We need good suggestions about how to bring shade surfaces into the file in a proper manner. Any thoughts?

**Comment by bwelle** [comment] 2017-10-14 06:23
@theo-armour 

Here are some clear issues I see with the Build Well gbXML for a box building with overhangs...

1. First, for adjacent buildings, you don't need to export the ground floor as a shading object. It serves no purpose. And as I mentioned before, zones can't be made for adjacent buildings. 

2. You don't have zones/space defined correctly. Each space/zone here needs to have 6 bounding surfaces...4 walls, a roof, and a floor. Since you don't split the roof into 5 separate surfaces, when you click on the roof surface, you see it is only assigned to Space.4 and nothing else. Space.1, Space.2, Space.3, and Space. 5 have no roof assigned. That's the first problem.

3. Second problem, same as above for the floor. The entire floor needs to split into 5 surfaces, each referencing a specific zone, otherwise you have what you have now...The floor only bounding Space.5.

4. You are missing the diagonal walls, 4 of them. These are required to appropriate bound each space. Generate those interior walls, then assign the to the appropriate spaces.

5. I do see that the overhangs are not being exported. I'm not sure why. Looking into it.

**Comment by mdengusiak** [comment] 2017-10-14 06:43
@theo-armour 
Bwelle is correct I was referring to the main building and zones naming strategy. Context building just shades

**Comment by theo-armour** [comment] 2017-10-14 09:30
@bwelle @mdengusiak 

I thought the FZK errors were due issues with shade type surfaces.

I am in the process of preparing a file with all that I know about gbXML. As you may surmise, it is not a long file. ;-)

This brings up a more important point. At this stage, particularly in a fast project like this, bug reports are not that useful. The developer usually already know most of the bugs and in the process of fixing them or doing something fun so they don't even begin to exist or whatever.

The main thing that is needed is guidance as to what are the right things to be doing.

For example. I would be delighted to see full examples of a space, a zone and a storey that you feel we should start with. Examples for different surfaces would be nice too. No, a link to a file that has all of these is not needed. A good, single, valid example of the basic needs would be great. Later, examples of fully features elements will happen too.

Of course, if you cannot do something essential or there is a real crash, then please do report.

But let's look at it another way: suppose you have been coding hard, you fix a ton of things, and you add a bunch of great new features. And all you get back is bug reports: bummer.

Things to consider:

* A good number of the items mentioned above are already on the read me files
* Every bug report that the developer responds to ( and I try to respond quickly ) means the developer is not coding the fixes
* Software has many fearful aspects, but handled properly it truly can create joy. Be part of finding the delight - even if it's a disaster

But let's look at it another, another way:

There's nothing sadder than writing something and there's nobody there.

So send in those bug reports faster miles an hour!

;-) 

written at 2:30 am

**Comment by mdengusiak** [comment] 2017-10-15 19:53
@theo-armour 
please make sure you have a rest and not overworked your self... take a day or two to relax. It is the last thing we would like to see you exhausted ;) we need you!

**Closed** 2017-10-25 06:03 UTC
Labels: updates
