### ISSUE TITLE
Openings are surfaces

### ISSUE THREAD

**Issue by EK-CEL** [ladybug-tools/spider#123] opened 2018-05-24 12:48 UTC
Here is a scenario: I want to see surfaces for the Storey 1 only. I activate it in [Reports]. Now I see shaded surfaces for that storey and the rest of the storeys are shown with edges. Except openings: they still are shaded:
![image](https://user-images.githubusercontent.com/39136340/40485986-0182959c-5f2e-11e8-8d60-e445fc14bae2.png)
It is not expected.
I believe we can consider an opening as kind of surface, it is flat. So I expect similar behavior for it. Also a surface and an opening are in parent-child relationship. If a wall is shown with edges, then its sub-components like openings (doors and windows) should follow the parent's setting and be displayed with edges.

**Comment by EK-CEL** [comment] 2018-05-24 13:02
There is another issue related to that. I hide interior walls and expect that openings belonging the walls disappear with the walls. Unfortunately they don't do that for the moment.
![image](https://user-images.githubusercontent.com/39136340/40486945-b4f18f14-5f30-11e8-93dc-4c45bd3b5005.png)
I found it very distracting on model review. 
Please make openings disappearing with parent wall, it will help to focus on envelope surfaces only.

**Comment by theo-armour** [comment] 2018-05-24 23:45
@EK-CEL 

Thank you for the heads-up. Openings are a new element in the Viewer. A nice workflow is still a work-in-progress. I also can end up clicking all over the place to get the view that is needed. ;-) So do keep reporting.

I think I have fixed the issues in your first comment.

I'm not certain about how to reproduce the issue in your second comment. In any case, openings have their own toggle buttons in all three menus so their visibility can be set independently of other surfaces.

![image](https://user-images.githubusercontent.com/547626/40518946-e040d0bc-5f71-11e8-8f88-0eaf2684f626.png)

**Comment by EK-CEL** [comment] 2018-05-25 17:57
@theo-armour 
Here is the [video](https://www.screencast.com/t/QiHn5X6FpO) demonstrating how we can hide interior walls, but not openings in those walls.

**Comment by EK-CEL** [comment] 2018-05-25 18:09
Is the issue with opening for hidden storeys fixed for the version 13.27?
I am asking because I still can see them. Here is the [video](https://www.screencast.com/t/X3nrjo5kX).

**Comment by theo-armour** [comment] 2018-05-26 22:43
Thanks for the video. I get the picture

i will look into fixing this. Openings are a new feature. It may take me a
while to get to grips with it all



PS. It took me a while to get my Flash player going again so I could view
the video on Screencast.

**Comment by theo-armour** [comment] 2018-05-29 22:15
@EK-CEL 

I looked into the openings visible on hidden storeys issue and it will be fixed. But this will most likely come in with R14 because that will have 'smarter' clickable openings and more.

And, not to worry about delays, R14 is already cooking.

**Comment by theo-armour** [comment] 2018-09-06 01:35
Generally, handling of openings as objects is progressing well, though the effort not complete

**Closed by theo-armour** 2018-09-06 01:35 UTC
